Update upstream NetBSD from git 0896a89cec2a8df05d7129d749231fe1712b0ad7
This correspond to master as of 2024-12-12 20:06:00.

diff --git a/buildrump.sh/src/usr.sbin/etcupdate/etcupdate b/buildrump.sh/src/usr.sbin/etcupdate/etcupdate
--- a/buildrump.sh/src/usr.sbin/etcupdate/etcupdate
+++ b/buildrump.sh/src/usr.sbin/etcupdate/etcupdate
@@ -1,8 +1,8 @@
 #!/bin/sh
 #
-# $NetBSD: etcupdate,v 1.61 2020/12/02 14:20:20 wiz Exp $
+# $NetBSD: etcupdate,v 1.65 2022/01/17 08:47:03 lukem Exp $
 #
-# Copyright (c) 2001-2008 The NetBSD Foundation, Inc.
+# Copyright (c) 2001-2022 The NetBSD Foundation, Inc.
 # All rights reserved.
 #
 # This code is derived from software contributed to The NetBSD Foundation
@@ -80,43 +80,52 @@ NEED_PWD_MKDB=false
 NEED_SERVICES_MKDB=false
 
 
-usage() {
-	cat << EOF >&2
+help()
+{
+	cat << EOF
 
-Usage: ${PROG} [options]
+Usage: ${PROG} [-alv] [-d DESTDIR] [-p PAGER] [-s SRC_ARG] [-t TEMPROOT] [-w WIDTH]
+       ${PROG} ( -h | -? )
 
 Options:
 
-  -p pager     Which pager to use              (default: /usr/bin/more)
-  -s {srcdir|tgzfile|tempdir}                  (default: /usr/src)
-               Location of the source files.  This may be any of the
-               following:
-               * A directory that contains a NetBSD source tree;
-               * A distribution set file such as "etc.tgz" or
-                 "xetc.tgz".  Pass multiple -s options to specify
-                 multiple such files;
-               * A temporary directory in which one or both of
-                 "etc.tgz" and "xetc.tgz" have been extracted.
-  -t temproot  Where to store temporary files  (default: /tmp/temproot)
-  -d destdir   Destination directory to check. (default: /)
-  -w width     Screen width                    (default: 80)
-  -a           Automatically update unmodified files
+  -a           Automatically update unmodified files.
+  -d DESTDIR   Destination directory to check. [/]
+  -h           Display this help, and exit.
   -l           Automatically skip files with strictly local changes
-               (this option has no effect on files lacking RCS Ids)
-  -h           This help text
-  -v           Be more verbose
+               (this option has no effect on files lacking RCS Ids).
+  -p PAGER     Which pager to use              [/usr/bin/more]
+  -s SRC_ARG   Location of the source files.   [/usr/src]
+               This may be any of the following:
+                 -s SRC_DIR   A directory that contains a NetBSD
+                              source tree.
+                 -s TGZ_DIR   A directory in which one or both of
+                              "etc.tgz" and "xetc.tgz" have been extracted.
+                 -s TGZ_FILE  A distribution set file such as "etc.tgz" or
+                              "xetc.tgz".  May be specified multiple times.
+  -t TEMPROOT  Where to store temporary files. [/tmp/temproot]
+  -w WIDTH     Screen width.                   [80]
+  -v           Be more verbose.
+  -?           Display this help, and exit.
 
 EOF
+}
+
+usage()
+{
+	help 1>&2
 	exit 1
 }
 
-verbose() {
+verbose()
+{
 	# $* = message to display if in verbose mode
 
 	${VERBOSE} && echo "${@}"
 }
 
-yesno() {
+yesno()
+{
 	# $* = message to display
 
 	echo -n "${@}? (y/[n]) "
@@ -191,7 +200,8 @@ bre_quote()
 	printf "%s\n" "${arg}" | sed -e 's/[][^$.*\\'"${extra}"']/\\&/g'
 }
 
-install_dir() {
+install_dir()
+{
 	# $1 = target directory (relative to ${DESTDIR})
 
 	NEED_ANYTHING=true
@@ -202,7 +212,8 @@ install_dir() {
 	fi
 }
 
-install_file() {
+install_file()
+{
 	# $1 = target file (relative to ${DESTDIR})
 
 	NEED_ANYTHING=true
@@ -230,7 +241,8 @@ install_file() {
 	esac
 }
 
-install_checksum() {
+install_checksum()
+{
 	# $1 = target file (relative to ${DESTDIR})
 
 	${AUTOMATIC} || return
@@ -248,7 +260,8 @@ install_checksum() {
 }
 
 # Initialise the DIFF_EXTRA_OPTIONS variable.
-init_diff_extra_options() {
+init_diff_extra_options()
+{
 	#
 	# Start with a few options that are always available.
 	#
@@ -274,7 +287,8 @@ init_diff_extra_options() {
   scommand Show differences using the specified diff-like command"
 }
 
-diff_and_merge_file() {
+diff_and_merge_file()
+{
 	# $1 = target file (relative to ${DESTDIR})
 
 	if cmp -s "${TEMPROOT}${1}" "${DESTDIR}${1}"; then
@@ -432,7 +446,8 @@ EOF
 }
 
 # Set the environment for make.
-set_makeenv() {
+set_makeenv()
+{
 	#
 	# INSTALL_DONE=1 prevents installation of unwanted
 	# files (things that are not part of the etc set).
@@ -462,7 +477,7 @@ USERRC="${HOME}/.{PROG}rc"
 [ -r ${USERRC} ] && . ${USERRC}
 
 # Read command line arguments
-while getopts ad:hlp:s:t:vw: i
+while getopts :ad:hlp:s:t:vw: i
 do
 	case "${i}" in
 	a)
@@ -472,7 +487,8 @@ do
 		DESTDIR="${OPTARG}"
 		;;
 	h)
-		usage
+		help
+		exit 0
 		;;
 	l)
 		LOCALSKIP=true
@@ -523,13 +539,31 @@ do
 	w)
 		WIDTH="${OPTARG}"
 		;;
-	*)
-		# getopts should already have printed an error message
+	"?")
+		if [ "${OPTARG}" = "?" ]; then
+			help
+			exit 0
+		fi
+		echo 1>&2 "${PROG}: Unknown option -${OPTARG}"
 		usage
-		break
+		;;
+
+	:)
+		echo 1>&2 "${PROG}: Missing argument for option -${OPTARG}"
+		usage
+		;;
+
+	*)
+		echo 1>&2 "${PROG}: Unimplemented option -${i}"
+		exit 3
 		;;
 	esac
 done
+shift $((${OPTIND} - 1))
+if [ $# -ne 0 ] ; then
+	echo 1>&2 "${PROG}: Unknown extra arguments"
+	usage
+fi
 
 # Last minute sanity checks
 if [ "$(id -u)" -ne 0 ]; then
@@ -539,7 +573,7 @@ fi
 DESTDIR="${DESTDIR%/}" # remove trailing slash, if any.  result might be "".
 DESTDIR_BRE="$(bre_quote "${DESTDIR}")"
 if [ "${N_SRC_ARGS}" -gt 1 ] && ( ${SOURCEMODE} || ${BINARYDIRMODE} ); then
-	echo "*** ERROR: Multiple -s args are allowed only with tgz files"
+	echo 1>&2 "${PROG}: Multiple -s args are allowed only with tgz files"
 	usage
 fi
 case "${TEMPROOT}" in
